# new_number = int(input('Введите число: '))
# print(new_number)
# input(a)
# new_number = int(input('Введите второе число: '))
# print(new_number)
# print(b)
# new_number = int(input('Введите третье число: '))
# print(new_number)
# print(c)
# new_number = int(input('Введите четвертое число: '))
# print(new_number)
# print(d)
# print(a + b) % (c * d)